version: '3'
services:
  #  Postgres database for Inventory
  db-inventory:
    container_name: db-inventory
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_inventory
      POSTGRES_USER: orbe
      POSTGRES_PASSWORD: 123456
    ports:
      - 5431:5431
    expose:
      - 5431
    command: -p 5431

  #  MySQL database for Orders
  db-orders:
    container_name: db-orders
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ms_orders
      MYSQL_USER: orbe
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3366:3306
    expose:
      - 3366

  #  Postgres database for Inventory
  db-products:
    container_name: db-products
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_products
      POSTGRES_USER: orbe
      POSTGRES_PASSWORD: 123456
    ports:
      - 5432:5432
    expose:
      - 5432
    command: -p 5432