version: '3'
services:
  #  Postgres database for Inventory
  db-inventory:
    container_name: db-inventory
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_inventory
      POSTGRES_USER: orbe
      POSTGRES_PASSWORD: 123456
    ports:
      - "5431:5431"
    expose:
      - 5431
    command: -p 5431

  #  MySQL database for Orders
  db-orders:
    container_name: db-orders
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ms_orders
      MYSQL_USER: orbe
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3366:3306"
    expose:
      - 3366

  #  Postgres database for Products
  db-products:
    container_name: db-products
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ms_products
      POSTGRES_USER: orbe
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    expose:
      - 5432
    command: -p 5432

  # Postgres database for Keycloak
  db-keycloak:
    container_name: db-keycloak
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: dbkeycloak
      POSTGRES_USER: orbe
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5433"
    expose:
      - 5433
    command: -p 5433

  # Keycloak
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.3
    command: ["start-dev"]
    ports:
      - "8181:8181"
    expose:
      - 8181
    depends_on:
      - db-keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: db-keycloak
      DB_DATABASE: db_keycloak
      DB_PORT: 5433
      DB_USER: orbe
      DB_PASSWORD: 123456
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_PORT: 8181